# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = " Home"
  url = "#slider"
  weight = 10
  pre = "<i class=\"fas fa-home fa-lg\"></i>"

[[main]]
  name = "The Story"
  url = "#summary"
  weight = 20

[[main]]
  name = "The Geminates"
  url = "#gallery"
  weight = 30

[[main]]
#  identifier = "projects"
  name = "The Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "People"
  url = "authors/"
  weight = 60

[[main]]
  name = "<i class=\"fas fa-envelope fa-lg\"></i>"
  url = "contact/"
  post = ""
  weight = 100

[[main]]
  name = " "
  identifier = "github"
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  url = "https://github.com/istmobiome/web"
  weight = 110

[[main]]
  parent = "More"
  name = "Workshops"
  url = "workshops/"
  weight = 150

[[main]]
  name = " "
  identifier = "water"
  pre = "<i class=\"fas fa-water fa-lg\"></i>"
  url = "projects/trans-water/"
  weight = 180

# To setup a dropdown menu set "identifier " in "parent" and reference
# parent in child
#[[main]]
#  parent = "projects"
#  name = "Project1"
#  url = "#projects"
#  weight = 41

#[[main]]
#  parent = "projects"
#  name = "Project2"
#  url = "#projects"
#  weight = 42


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

# This will add a menu to a docs/ directory
# # Documentation
#
# [[docs]]
#   name = "Overview"
#   weight = 10
#   url = "/docs/"
#
# [[docs]]
#   name = "Getting Started"
#   weight = 20
#   identifier = "setup"
#
# [[docs]]
#   name = "Create Content"
#   weight = 30
#   identifier = "content"
#
# [[docs]]
#   name = "Deployment"
#   weight = 40
#   identifier = "deploy"
#
# [[docs]]
#   name = "Features"
#   weight = 50
#   identifier = "features"
#
# [[docs]]
#   name = "Migrate"
#   identifier = "migrate"
#   weight = 60
#
# [[docs]]
#   name = "Contributing"
#   url = "/docs/contribute/"
#   weight = 70
#
# [[docs]]
#   name = "Troubleshooting"
#   weight = 80
#   url = "/docs/faq/"
