# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = " Home"
  url = "#hero"
  weight = 10
  pre = "<i class='fas fa-home fa-lg'></i>"

[[main]]
  name = "Posts"
  url = "post/"
  weight = 20

[[main]]
  name = "Projects"
  url = "#project"
  weight = 30

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 50

[[main]]
  name = "Post2"
  url = "post/"
  weight = 80

[[main]]
  name = "Projects2"
  url = "project/"
  weight = 90

[[main]]
  pre = "<i class='fab fa-github fa-lg '></i>"
  name = "  "
  url = "https://github.com/istmobiome/web/"
  weight = 240

[[main]]
  name = ""
  url = "contact/"
  weight = 250
  pre = "<i class='fas fa-envelope fa-lg'></i>"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
